version: '3.7'

services:
  database:
    image: postgres
    container_name: sysdelta
    restart: always
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=sysdelta_docker
      - POSTGRES_DB=sysdelta_docker
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - sysdelta-network
  redis:
    container_name: sysdelta-redis
    image: redis:alpine
    ports:
      - 6379:6379
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sysdelta-network
    restart: unless-stopped
    depends_on:
      - database

networks:
  sysdelta-network:
    driver: bridge
volumes:
  pgadmin_data:
    driver: local
  pgdata:
    driver: local